{
  "buildCommand": "cd milestone\\ 3/backend && npm install",
  "buildDirectory": "",
  "devCommand": "cd milestone\\ 3/backend && npm run dev",
  "envVars": [
    {
      "key": "DB_HOST",
      "value": "datastoredb-datastorev1.h.aivencloud.com",
      "isFile": false
    },
    {
      "key": "DB_PORT",
      "value": "17687",
      "isFile": false
    },
    {
      "key": "DB_USER",
      "value": "avnadmin",
      "isFile": false
    },
    {
      "key": "DB_PASSWORD",
      "value": "YOUR_AIVEN_DB_PASSWORD_HERE",
      "isFile": false
    },
    {
      "key": "DB_NAME",
      "value": "datagov_db",
      "isFile": false
    },
    {
      "key": "PORT",
      "value": "5000",
      "isFile": false
    },
    {
      "key": "CORS_ORIGIN",
      "value": "YOUR_RENDER_FRONTEND_URL",
      "isFile": false
    }
  ],
  "name": "DataStore Backend",
  "plan": "free",
  "preDeployCommand": "cd milestone\\ 3/backend && npm install",
  "publish": "backend"
}
